### PR TITLE
[FE] Batching functionality

### LINKED ISSUE #34: Countdown for time left is not working
> The counter 2 minutes left is stuck

@osmaczko I see it get stuck. Could you please confirm that's something you've tested as part of https://github.com/status-im/community-dapp/issues/7 and that it was working before?

_Originally posted by @felicio in https://github.com/status-im/community-dapp/pull/31#discussion_r1187554720_

### LINKED ISSUE #62: The button says "Finalize Weekly featured" instead of "Verify Weekly featured"
I gave it a second try and identified one critical issue, although I don't want to block this PR any longer. We should address it in followup.

https://github.com/status-im/community-dapp/assets/33099791/649cc729-644a-4010-8e10-83e1ac69fe3e

2) The button says "Finalize Weekly featured" instead of "Verify Weekly featured", this seems to be state update issue.

_Originally posted by @osmaczko in https://github.com/status-im/community-dapp/issues/37#issuecomment-1613147017_

### LINKED ISSUE #79: Update App to cast and finalize Waku votes in batches
Previously, all votes gathered from the Waku were cast and finalized in a single transaction. This approach posed a [risk](https://github.com/status-im/community-dapp/issues/65) of running out of gas. To address this, we've [modified](https://github.com/status-im/community-dapp/pull/72) the contracts to cast and finalize votes in batches, ensuring that we won't exhaust the gas in a single transaction.

The application now needs to be updated to reflect this change in voting mechanics:
- adapt the logic to cast Waku votes in batches
- update the UI to inform users about the batch processing of votes. Specifically, users should be notified if there are remaining batches that still need processing

### PR DESCRIPTION
**Pull request by jkbktl**
✅ This PR:
- adds batching functionality for verification and finalization of both basic voting and featured voting (closes #79)
- recovers `<NotifcationList />` for basic voting
- fixes issue when countdown stopped counting down during voting (closes #34)
- fixes issue when voting got wrong state, so it showed wrong copy (closes #62)
- fixes wrong copy for featured section when no community is featured
- fixes `getActiveVotingRooms()` in `VotingContract`, which was causing disappearing of Voting Rooms after first batch of finalization
- fixes - other small design tweaks

⚠️ Known issue:
- during finalization of the basic voting, it seems like some "votes" are lost, but it's just showing already finalized votes, after another batch it adds these votes up and so on (not ideal, not a blocker though)

### CODE REVIEW

File: packages/DApp/src/components/directory/DirectoryInfo.tsx
Comment (felicio) [inline packages/DApp/src/components/directory/DirectoryInfo.tsx:1]: non-blocking: could the batching logic be in a hook or at least a separate function? especially since I believe it's copied and used elsewhere too.

File: packages/DApp/src/hooks/useTimeLeft.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
+import { useEffect, useState } from 'react'
+
+export function useTimeLeft(timeEndAt: number): number {
+  const [timeLeft, setTimeLeft] = useState(timeEndAt - Math.floor(Date.now() / 1000))
+
+  useEffect(() => {
+    const timer = setInterval(() => setTimeLeft(timeEndAt - Math.floor(Date.now() / 1000)), 1000)
+
+    return () => {
+      if (timer) clearInterval(timer)
```
Comment (felicio) [inline packages/DApp/src/hooks/useTimeLeft.ts:10]: non-blockig: `timer` would be always defined, no

File: packages/DApp/src/components/directory/DirectoryInfo.tsx [hunk 2]
```diff
@@ -15,12 +15,51 @@ export function DirectoryInfo() {
...
+    ? Math.min(votesCount, config.votesLimit)
+    : Math.min(votesLeftCount, config.votesLimit)
+  const batchCount = Math.ceil((beingFinalized ? votesCount + 1 : votesCount) / config.votesLimit)
+  const batchLeftCount = Math.ceil(votesLeftCount / config.votesLimit)
+
+  const batchDoneCount = batchCount - batchLeftCount
+
+  useEffect(() => {
+    if (finalizeVoting.state.status === 'Success' || castVotes.state.status === 'Success') {
+      history.go(0)
```
Comment (felicio) [inline packages/DApp/src/components/directory/DirectoryInfo.tsx:60]: please, could you explain me why are `history` statements necessary?

File: packages/DApp/src/hooks/useFeaturedVotes.ts [hunk 3]
```diff
@@ -56,7 +56,7 @@ export function useFeaturedVotes() {
 
     loadFeatureVotes()
 
-    const task = setInterval(loadFeatureVotes, 10000)
+    const task = setInterval(loadFeatureVotes, 5000)
```
Comment (felicio) [inline packages/DApp/src/hooks/useFeaturedVotes.ts:59]: why decreasing the interval? given the `history` statements (https://github.com/status-im/community-dapp/pull/88/files#r1377631506) aren't those enough of a workaround already?

File: packages/DApp/src/components/directory/DirectoryInfo.tsx (hunk 2 above)
Comment (jkbktl) [reply packages/DApp/src/components/directory/DirectoryInfo.tsx:60]: When I get Success 'state' page is not re-rendered automatically, therefore we leverage this workaround to refresh page, so user can see current state.

File: packages/DApp/src/hooks/useFeaturedVotes.ts (hunk 3 above)
Comment (jkbktl) [reply packages/DApp/src/hooks/useFeaturedVotes.ts:59]: It's different kind of story. This updates votes (and everything related) in UI from waku. So if someone votes during my visit at this page, it updates votes for me as well.

**Comment by jkbktl** [comment]
There are currently two bugs:

a. This one is mentioned in the description on the top of the PR. It's related to counting votes. For some reason, during finalization phase, only "saved" votes from contract are shown. Every batch of finalization adds up new votes (included in that specific batch). You can reproduce it during every basic vote, it's visible without any specific actions.

b. Second bug happens when verification was not processes completely, meaning not all batches were sent to contract and therefore not all votes were verified during verification phase. It makes impossible for FE to evaluate verified votes in batches, because we are not able to figure it out how many votes was verified. In case it's just one batch we can use `evaluatingPos` to finalize voting, but even in that case it means that not all votes are counted for that specific voting. It should be reproducible by these steps (in local environment with hard limit 2 votes per one batch):
	1. create voting with initial vote
	2. vote at least by three other accounts, which means there will be at least 2 batches
	3. go through verification phase without clicking on button "verify"
	4. try to finalize voting
	5. it should throw an error `limit is greater than votes length`, because FE expects there's 4 votes (1 initial + 3 other) so it sends hard limit 2, but in reality, there's only 1 initial vote, which causes an error.

File: packages/DApp/src/hooks/useFeaturedVotes.ts (hunk 3 above)
Comment (felicio) [reply packages/DApp/src/hooks/useFeaturedVotes.ts:59]: Right, but if I understand the workaround correctly, it will update the votes for you after you've interacted with the contract. Letting you know about the updates done or new action to be taken then.

The reason I pointed this line out is that I'm convinced it puts even more stress on the node. Instead of changing the Waku protocol if optimizations in this case are to be made.

> consider replacing setInterval(get, 10000) for Filter protocol and use Store only on initial load – https://github.com/status-im/status-desktop/issues/7534#issuecomment-1330515894

Comment (jkbktl) [reply packages/DApp/src/hooks/useFeaturedVotes.ts]: reverted https://github.com/status-im/community-dapp/pull/88/commits/ff3a9468526c5598655df46d43a14632366b0bd1

File: packages/DApp/src/hooks/useTimeLeft.ts (hunk 1 above)
Comment (jkbktl) [reply packages/DApp/src/hooks/useTimeLeft.ts]: addresed https://github.com/status-im/community-dapp/pull/88/commits/ff3a9468526c5598655df46d43a14632366b0bd1

File: packages/DApp/src/components/directory/DirectoryInfo.tsx
Comment (jkbktl) [reply packages/DApp/src/components/directory/DirectoryInfo.tsx:1]: addresed https://github.com/status-im/community-dapp/pull/88/commits/ff3a9468526c5598655df46d43a14632366b0bd1

**Review by felicio — APPROVED** [review]
